<a href="<?php echo BASE_DIR ?>">Home</a> | 
<a href="<?php echo BASE_DIR ?>?c=User">User</a> |
<a href="<?php echo BASE_DIR ?>?c=Groups">Groups</a> |
<a href="<?php echo BASE_DIR ?>?c=Administrator">Administrator</a> |
<a href="<?php echo BASE_DIR ?>?c=Country">Country</a> |
<a href="<?php echo BASE_DIR ?>?c=Member">Member</a> |
<a href="<?php echo BASE_DIR ?>?c=GroupDetails">GroupeDetails</a> |
<a href="<?php echo BASE_DIR ?>?c=File">File</a> |
<a href="<?php echo BASE_DIR ?>?c=Comment">Comment</a> |
<a href="<?php echo BASE_DIR ?>?c=Moderator">Moderator</a> |